#! /bin/sh
### BEGIN INIT INFO
# Provides:          pysshrpd
# Required-Start:    $network $named $remote_fs $syslog
# Required-Stop:     $network $named $remote_fs $syslog
# Should-Start:      pysshrpd
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/bin/pysshrpd
DAEMON_OPTS="-c /etc/pysshrp/config.py -l /var/log/pysshrpd.log"
NAME="pysshrpd"
DESC="pysshrpd"
PIDFILE="/var/run/${NAME}.pid"

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
    start)
        log_begin_msg "Starting $DESC"
        start-stop-daemon --start --background --quiet --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
        log_end_msg $?
    ;;
    stop)
        log_begin_msg "Stopping $DESC"
        start-stop-daemon --stop --retry TERM/10/KILL/5 --quiet --oknodo --pidfile $PIDFILE
        log_end_msg $?
    ;;
    reload)
        log_begin_msg "Reloading $DESC"
        start-stop-daemon --stop --signal HUP --quiet --oknodo --pidfile PIDFILE
        log_end_msg $?
    ;;
    status)
        status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
    ;;
    restart)
        log_begin_msg "Restarting $DESC"
        start-stop-daemon --stop --retry TERM/10/KILL/5 --quiet --oknodo --pidfile $PIDFILE
        start-stop-daemon --start --background --quiet --oknodo --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
        log_end_msg $?
    ;;
    *)
        echo "Usage: $0 {start|stop|status|restart}" >&2
        exit 1
    ;;
esac
